guest_list = ['pimp c', 'lil boosie', 'tupac shakur']
guest_list.insert(0, 'kendrick lamar')
guest_list.insert(2, 'bun b')
guest_list.append('master p')
print("Can only invite 2 people")
popped_guests = guest_list.pop(0)
print(f"{popped_guests} can't come")
popped_guests = guest_list.pop(0)
print(f"{popped_guests} can't come")
popped_guests = guest_list.pop(0)
print(f"{popped_guests} can't come")
popped_guests = guest_list.pop(0)
print(f"{popped_guests} can't come")
print(guest_list)

