locs = ['japan', 'china', 'russia', 'serbia', 'indonesia']
print(locs)
print(sorted(locs))
print(locs)
print(sorted(locs, reverse=True))
print(locs)
locs.reverse()
print(locs)
locs.reverse()
print(locs)
locs.sort()
print(locs)
locs.sort(reverse=True)
print(locs)
